version: '3.3'
services:
    openaiphoenixbot:
        build:
            args:
                BASE_VERSION: '17.4-alpine'
            context: ./
            dockerfile: docker/Dockerfile

        environment:
            BOT_DAILY_GREENTEXT_CRON: ${BOT_DAILY_GREENTEXT_CRON-0 19 * * *}
            BOT_ACTIVITY: ${BOT_ACTIVITY-conquer the world}
            BOT_CHANNEL_ID: ${BOT_CHANNEL_ID?Please provide a channel id}
            BOT_TOKEN: ${BOT_TOKEN?Please provide a bot token}
            OPENAI_API_KEY: ${OPENAI_API_KEY?Please provide an OpenAI API key}
