version: '3.3'
services:
    open-ai-phoenix-bot:
        build:
            args:
                BASE_VERSION: '17.4-alpine'
            context: ./
            dockerfile: docker/Dockerfile

        restart: unless-stopped

        environment:
            BOT_GREENTEXT_CRON: ${BOT_GREENTEXT_CRON-0 19 * * *}
            BOT_ACTIVITY: ${BOT_ACTIVITY-conquer the world}
            BOT_CHANNEL_ID: ${BOT_CHANNEL_ID?Please provide a channel id}
            BOT_TOKEN: ${BOT_TOKEN?Please provide a bot token}
            OPENAI_API_KEY: ${OPENAI_API_KEY?Please provide an OpenAI API key}
