version: '3.3'
services:
    open-ai-phoenix-bot:
        build:
            args:
                BASE_VERSION: '17.4-alpine'
            context: ./
            dockerfile: docker/Dockerfile

        restart: unless-stopped

        environment:
            DISCORD_BOT_GREENTEXT_CRON: ${DISCORD_BOT_GREENTEXT_CRON-0 17 * * *}
            DISCORD_BOT_WIKI_CRON: ${DISCORD_BOT_WIKI_CRON-0 16 * * *}
            DISCORD_BOT_ACTIVITY: ${DISCORD_BOT_ACTIVITY-conquer the world}
            DISCORD_BOT_CHANNEL_ID: ${DISCORD_BOT_CHANNEL_ID?Please provide a channel id}
            DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN?Please provide a bot token}
            DISCORD_APP_ID: ${DISCORD_APP_ID?Please provide a application id}
            OPENAI_API_KEY: ${OPENAI_API_KEY?Please provide an OpenAI API key}
