ARG BASE_VERSION=17.4-alpine

FROM node:${BASE_VERSION} as build

WORKDIR /app

COPY package*.json tsconfig*.json ./
RUN npm ci --ignore-scripts

COPY src src
RUN npm run build

FROM node:${BASE_VERSION}

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./

RUN npm ci --ignore-scripts --only=production

CMD ["npm", "run", "start"]
